/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import bo.SystemManagement;
import db.DataAccessObject;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jdk.nashorn.internal.ir.BreakNode;

/**
 *
 * @author phamquangkhang
 */
public class FrmManager extends javax.swing.JFrame {

    private SystemManagement sm;
    private DefaultTableModel dtm;
    private DataAccessObject dao;

    private final String[] StaffCol = {"username", "fullname", "gender", "dob", "email", "phone_num", "address", "isBlock", "password", "isManager"};
    private final String[] StaffColRef = {"Tên Tài Khoản", "Họ và Tên", "Giới tính", "Ngày Sinh", "Email", "Số điện thoại", "Địa chỉ", "Tài khoản bị khóa?"};
    private boolean staffIsLoad = false;

    private final String[] CustomerCol = {"cardID", "score", "accountType", "name", "gender", "passport", "dob", "phoneNumber", "email"};
    private final String[] CustomerColRef = {"Mã số thẻ", "Điểm tích", "Loại Tài Khoản", "Họ và Tên", "Giới tính", "CMND/Passport", "Ngày sinh", "Số điện thoại", "Email"};
    private boolean customerIsLoad = false;

    private String[] currentCol = StaffCol;
    private String[] currentColRef = StaffColRef;
    private String currentTable = "Staff";

    private String currentUser;
    private String currentRole;

    private String buildingSQLSelectToBindTable(String[] inArr, String tableName) {
        String ret = "select";
        for (String string : inArr) {
            ret += " " + string + ",";
        }
        ret = ret.substring(0, ret.length() - 1) + " from " + tableName;
        return ret;
    }

    /**
     * Creates new form manager_form
     */
    public FrmManager(String username, String role) {
        currentUser = username;
        currentRole = role;
        try {
            dao = new DataAccessObject();
            sm = new SystemManagement();
        } catch (Exception e) {
            System.out.println("clgv");
            JOptionPane.showMessageDialog(this, e.getMessage());
            System.exit(0);
        }
        initComponents();
        if (currentRole.equalsIgnoreCase("staff")) {
            tabbedPanel.remove(2);
        }
//        jScrollPane1.setVisible(false);
//        buildingSQLSelectToBindTable(StaffCol, "Staff");
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Hệ thống quản lý rạp CGV");
    }

    private void loadData() {
        String sqlSelect = buildingSQLSelectToBindTable(currentCol, currentTable);
        System.out.println(sqlSelect);
        for (String string : currentColRef) {
            dtm.addColumn(string);
        }
        try {
//            dao = new DataAccessObject();
            ResultSet rs = dao.getResulSet(sqlSelect);

            while (rs.next()) {
                int count = 0;
                Object[] obj = new Object[currentCol.length];
                for (String string : currentCol) {
                    if (string.toLowerCase().startsWith("is")) {
                        obj[count++] = rs.getString(string).equalsIgnoreCase("0") ? "false" : "true";
                    } else {
                        obj[count++] = rs.getString(string);
                    }
                }
                dtm.addRow(obj);
            }
        } catch (Exception ex) {
//            JOptionPane.showMessageDialog(this, "Gặp lỗi trong quá trình lấy dữ liệu!!!");
            JOptionPane.showMessageDialog(this, ex.toString());
            return;

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogout = new javax.swing.JButton();
        tabbedPanel = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbCustomer = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbStaff = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnBlock = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLogout.setText("Đăng Xuất");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        tabbedPanel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabbedPanelStateChanged(evt);
            }
        });

        tbCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbCustomer.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tbCustomer.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbCustomer.getTableHeader().setResizingAllowed(false);
        jScrollPane2.setViewportView(tbCustomer);

        tabbedPanel.addTab("Khách Hàng", jScrollPane2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 964, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );

        tabbedPanel.addTab("Ticket", jPanel1);

        tbStaff.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tbStaff.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(tbStaff);

        tabbedPanel.addTab("Nhân viên", jScrollPane1);

        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnBlock.setText("Khóa");

        btnUpdate.setText("Sửa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBlock, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(tabbedPanel, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBlock, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedPanel))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        sm.logout(this);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private int btnShow(int caze) {
        switch (caze) {
            case 2:
            case 0:
                btnAdd.setVisible(true);
                btnUpdate.setVisible(true);
                btnBlock.setVisible(true);
                if (caze == 0) {
                    btnBlock.setVisible(false);
                }
                break;
            case 1:
                btnAdd.setVisible(false);
                btnUpdate.setVisible(false);
                btnBlock.setVisible(false);
                break;

        }
        return caze;
    }

    private void tabbedPanelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabbedPanelStateChanged
        // TODO add your handling code here:
        switch (btnShow(tabbedPanel.getSelectedIndex())) {
            case 2:
                dtm = (DefaultTableModel) tbStaff.getModel();
                currentCol = StaffCol;
                currentColRef = StaffColRef;
                currentTable = "Staff";
                if (!staffIsLoad) {
                    loadData();
                    staffIsLoad = true;
                }
                break;
            case 0:
                dtm = (DefaultTableModel) tbCustomer.getModel();
                currentCol = CustomerCol;
                currentColRef = CustomerColRef;
                currentTable = "Customer";
                if (!customerIsLoad) {
                    loadData();
                    customerIsLoad = true;
                }
                break;
            case 1:

                break;
        }
    }//GEN-LAST:event_tabbedPanelStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmManager("abc", "staff").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBlock;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane tabbedPanel;
    private javax.swing.JTable tbCustomer;
    private javax.swing.JTable tbStaff;
    // End of variables declaration//GEN-END:variables
}
